### PR TITLE
Do not define setFileSize when compiling with GHC < 8.10.6

### LINKED ISSUE #9: 0.2.4 fails to build with GHC 8.6.5 on Windows
Hello! The latest release fails to build with the following error:

```
 System\EasyFile\Missing.hs:180:10: error:
Error:     Variable not in scope:
      setFilePointerEx :: HANDLE -> Integer -> FilePtrDirection -> IO a0
    |
180 |     _ <- setFilePointerEx hdl (fromIntegral siz) fILE_CURRENT
    |          ^^^^^^^^^^^^^^^^
Error: Process completed with exit code 1.
```

This is because `setFilePointerEx` was added in Win32 2.6.2.0 (https://hackage.haskell.org/package/Win32-2.13.2.1/changelog), and GHC versions up to and including 8.10.5 bundle Win32 2.6.1.0. So the latest release can't be built with anything older than 8.10.6, which is quite unfortunate.

Is there any chance this could be fixed?

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #9.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
CI fails but leave it to me.

**Comment by kazu-yamamoto** [comment]
The CI passes on the master.
Thank you for your contribution!
